site_name: Otto Martinwall
site_url: https://GITHUB_USERNAME.github.io
site_author: Otto Martinwall
site_description: This is my work.

nav:
  - Home: index.md
  - Analysis: latex/university/analysis/markdown.md
  - 'My Projects'
    - Mattef√∂rklaringar: latex/projects/gymnasiestuff/markdown.md

theme:
  logo: img/largeSigma.png
  name: material
  palette: 
    - primary: blue grey